apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-test
spec:
  replicas: 1
  selector:
    app: jenkins-test-pod
  template:
    metadata:
      labels:
        app: jenkins-test-pod
    spec:
      containers:
      - name: jenkins
        image: jenkins:2.60.3
