apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30007
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: jenkins-test-pod
