apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ubuntu-ds
  labels:
    app: ubuntu-ds
spec:
  selector:
    matchLabels:
      name: ubuntu-ds
  template:
    metadata:
      labels:
        name: ubuntu-ds
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
